//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace iCirugiasXAF.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class Horario : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.Int32 _hora;
    private System.DateTime _fecha;
    private System.String _afanadora;
    private System.String _circulante2;
    private System.String _circulante1;
    private System.String _instrumentista;
    private System.String _ayudante3;
    private System.String _ayudante2;
    private System.String _ayudante1;
    private System.String _anestesia;
    private System.String _quirofano;
    private System.String _cirujano;
    private System.String _cirugia;
    private System.String _nombrePaciente;
    public Horario(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.DateTime Fecha
    {
      get
      {
        return _fecha;
      }
      set
      {
        SetPropertyValue("Fecha", ref _fecha, value);
      }
    }
    public System.Int32 Hora
    {
      get
      {
        return _hora;
      }
      set
      {
        SetPropertyValue("Hora", ref _hora, value);
      }
    }
    public System.String NombrePaciente
    {
      get
      {
        return _nombrePaciente;
      }
      set
      {
        SetPropertyValue("NombrePaciente", ref _nombrePaciente, value);
      }
    }
    public System.String Cirugia
    {
      get
      {
        return _cirugia;
      }
      set
      {
        SetPropertyValue("Cirugia", ref _cirugia, value);
      }
    }
    public System.String Cirujano
    {
      get
      {
        return _cirujano;
      }
      set
      {
        SetPropertyValue("Cirujano", ref _cirujano, value);
      }
    }
    public System.String Quirofano
    {
      get
      {
        return _quirofano;
      }
      set
      {
        SetPropertyValue("Quirofano", ref _quirofano, value);
      }
    }
    public System.String Anestesia
    {
      get
      {
        return _anestesia;
      }
      set
      {
        SetPropertyValue("Anestesia", ref _anestesia, value);
      }
    }
    public System.String Ayudante1
    {
      get
      {
        return _ayudante1;
      }
      set
      {
        SetPropertyValue("Ayudante1", ref _ayudante1, value);
      }
    }
    public System.String Ayudante2
    {
      get
      {
        return _ayudante2;
      }
      set
      {
        SetPropertyValue("Ayudante2", ref _ayudante2, value);
      }
    }
    public System.String Ayudante3
    {
      get
      {
        return _ayudante3;
      }
      set
      {
        SetPropertyValue("Ayudante3", ref _ayudante3, value);
      }
    }
    public System.String Instrumentista
    {
      get
      {
        return _instrumentista;
      }
      set
      {
        SetPropertyValue("Instrumentista", ref _instrumentista, value);
      }
    }
    public System.String Circulante1
    {
      get
      {
        return _circulante1;
      }
      set
      {
        SetPropertyValue("Circulante1", ref _circulante1, value);
      }
    }
    public System.String Circulante2
    {
      get
      {
        return _circulante2;
      }
      set
      {
        SetPropertyValue("Circulante2", ref _circulante2, value);
      }
    }
    public System.String Afanadora
    {
      get
      {
        return _afanadora;
      }
      set
      {
        SetPropertyValue("Afanadora", ref _afanadora, value);
      }
    }
  }
}
