//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace iCirugiasXAF.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class Programacion : XPObject
  {
    private System.DateTime _fechaNacimientoPaciente;
    private iCirugiasXAF.Module.BusinessObjects.Afanadora _afanadora;
    private iCirugiasXAF.Module.BusinessObjects.Enfermeria _circulante2;
    private iCirugiasXAF.Module.BusinessObjects.Enfermeria _circulante;
    private iCirugiasXAF.Module.BusinessObjects.Enfermeria _instrumentista;
    private iCirugiasXAF.Module.BusinessObjects.Enfermeria _ayudante3;
    private iCirugiasXAF.Module.BusinessObjects.Enfermeria _ayudante2;
    private iCirugiasXAF.Module.BusinessObjects.Enfermeria _ayudante1;
    private iCirugiasXAF.Module.BusinessObjects.Enfermeria _anestesia;
    private iCirugiasXAF.Module.BusinessObjects.Medico _cirujano;
    private iCirugiasXAF.Module.BusinessObjects.Quirofano _quirofano;
    private iCirugiasXAF.Module.BusinessObjects.Cirugia _cirugia;
    private System.String _nombrePaciente;
    private System.DateTime _fechayHora;
    public Programacion(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.DateTime FechayHora
    {
      get
      {
        return _fechayHora;
      }
      set
      {
        SetPropertyValue("FechayHora", ref _fechayHora, value);
      }
    }
    public System.String NombrePaciente
    {
      get
      {
        return _nombrePaciente;
      }
      set
      {
        SetPropertyValue("NombrePaciente", ref _nombrePaciente, value);
      }
    }
    public System.DateTime FechaNacimientoPaciente
    {
      get
      {
        return _fechaNacimientoPaciente;
      }
      set
      {
        SetPropertyValue("FechaNacimientoPaciente", ref _fechaNacimientoPaciente, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Cirugia Cirugia
    {
      get
      {
        return _cirugia;
      }
      set
      {
        SetPropertyValue("Cirugia", ref _cirugia, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Quirofano Quirofano
    {
      get
      {
        return _quirofano;
      }
      set
      {
        SetPropertyValue("Quirofano", ref _quirofano, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Medico Cirujano
    {
      get
      {
        return _cirujano;
      }
      set
      {
        SetPropertyValue("Cirujano", ref _cirujano, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Enfermeria Anestesia
    {
      get
      {
        return _anestesia;
      }
      set
      {
        SetPropertyValue("Anestesia", ref _anestesia, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Enfermeria Ayudante1
    {
      get
      {
        return _ayudante1;
      }
      set
      {
        SetPropertyValue("Ayudante1", ref _ayudante1, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Enfermeria Ayudante2
    {
      get
      {
        return _ayudante2;
      }
      set
      {
        SetPropertyValue("Ayudante2", ref _ayudante2, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Enfermeria Ayudante3
    {
      get
      {
        return _ayudante3;
      }
      set
      {
        SetPropertyValue("Ayudante3", ref _ayudante3, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Enfermeria Instrumentista
    {
      get
      {
        return _instrumentista;
      }
      set
      {
        SetPropertyValue("Instrumentista", ref _instrumentista, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Enfermeria Circulante
    {
      get
      {
        return _circulante;
      }
      set
      {
        SetPropertyValue("Circulante", ref _circulante, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Enfermeria Circulante2
    {
      get
      {
        return _circulante2;
      }
      set
      {
        SetPropertyValue("Circulante2", ref _circulante2, value);
      }
    }
    public iCirugiasXAF.Module.BusinessObjects.Afanadora Afanadora
    {
      get
      {
        return _afanadora;
      }
      set
      {
        SetPropertyValue("Afanadora", ref _afanadora, value);
      }
    }
  }
}
